version: '3'
services:
  app:
    container_name: sellers-service
    image: behive/sellers-service
    build: .
    volumes:
      - ".:/app"
      - node_modules:/app/node_modules
    ports:
      - 3000:3000
    command: npm run start-dev
    networks:
      - bridge
    environment:
      - PORT=3000
      - NODE_ENV=development
      - MONGO_URL=mongodb://mongo/sellers
      - PRODUCTS_SERVICE_HOST=sellers-products_service:3002
    depends_on:
      - mongo
  sellers-products_service:
    container_name: sellers-products_service
    image: behive/products-service
    ports:
      - 3002:3002
    networks:
      - bridge
    environment:
      - PORT=3002
      - NODE_ENV=development
      - MONGO_URL=mongodb://mongo/products
      - ELASTICSEARCH_HOST=elasticsearch
      - ELASTICSEARCH_PORT=9200
    depends_on:
      - mongo
      - elasticsearch
  mongo:
    container_name: sellers-mongo
    image: mongo
    volumes:
      - mongo_data:/data/db
    ports:
      - 3001:27017
    networks:
      - bridge
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.3
    container_name: sellers-elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 3003:9200
    networks:
      - bridge
volumes:
  node_modules:
  mongo_data:
  esdata:
networks:
  bridge: