version: '3'
services:
  app:
    container_name: sellers-service
    image: behive/sellers-service
    build: .
    volumes:
      - ".:/app"
      - node_modules:/app/node_modules
    ports:
      - 3000:3000
    command: npm run start-dev
    networks:
      - bridge
    environment:
      - PORT=3000
      - NODE_ENV=development
      - MONGO_URL=mongodb://mongo/sellers-test
      - PRODUCTS_SERVICE_HOST=localhost:3002
    depends_on:
      - mongo
      - sellers-products_service
  sellers-products_service:
    container_name: sellers-products_service
    image: behive/products-service
    ports:
      - 3002:3002
    networks:
      - bridge
    environment:
      - PORT=3002
      - NODE_ENV=development
      - MONGO_URL=mongodb://mongo/products-test
    depends_on:
      - mongo
  mongo:
    container_name: sellers-mongo
    image: mongo
    volumes:
      - mongo_data:/data/db
    ports:
      - 3001:27017
    networks:
      - bridge
volumes:
  node_modules:
  mongo_data:
networks:
  bridge: