version: '3'
services:
  app:
    container_name: sellers-service
    build: .
    volumes:
      - ".:/app"
      - node_modules:/app/node_modules
    ports:
      - 3000:3000
    command: npm run start-dev
    networks:
      - bridge
    environment:
      - PORT=3000
      - NODE_ENV=development
      - MONGO_URL=mongodb://mongo/sellers-test
    depends_on:
      - mongo
  mongo:
    container_name: sellers-mongo
    image: mongo
    volumes:
      - mongo_data:/data/db
    ports:
      - 3001:27017
    networks:
      - bridge
volumes:
  node_modules:
  mongo_data:
networks:
  bridge: